### ISSUE TITLE
Hallon on Heroku's Cedar Stack

### ISSUE THREAD

**Issue by chrblabla** [Burgestrand/Hallon#144]
Hi there!
After migrating to cedar and updating to the latest versions of Hallon (0.18.2) and Spotify (12.5.1), it somehow doesn't work anymore.
When I try to create a session step by step, this is what happens:

``` ruby
key = IO.read(ENV["SPOTIFY_APPKEY"]) # reads the binary file spotify_appkey.key
session = Hallon::Session.initialize key

NoMethodError: undefined method `[]' for nil:NilClass
    from /app/vendor/bundle/ruby/1.9.1/gems/spotify-12.5.1/lib/spotify/error.rb:41:in `disambiguate'
    from /app/vendor/bundle/ruby/1.9.1/gems/hallon-0.18.2/lib/hallon/error.rb:34:in `maybe_raise'
    from /app/vendor/bundle/ruby/1.9.1/gems/hallon-0.18.2/lib/hallon/session.rb:139:in `block (2 levels) in initialize'
    from /app/vendor/bundle/ruby/1.9.1/gems/hallon-0.18.2/lib/hallon/session.rb:138:in `initialize'
    from /app/vendor/bundle/ruby/1.9.1/gems/hallon-0.18.2/lib/hallon/session.rb:138:in `new'
    from /app/vendor/bundle/ruby/1.9.1/gems/hallon-0.18.2/lib/hallon/session.rb:138:in `block in initialize'
    from /app/vendor/bundle/ruby/1.9.1/gems/hallon-0.18.2/lib/hallon/observable.rb:161:in `subscribe_for_callbacks'
    from /app/vendor/bundle/ruby/1.9.1/gems/hallon-0.18.2/lib/hallon/session.rb:127:in `initialize'
    from /app/vendor/bundle/ruby/1.9.1/gems/hallon-0.18.2/lib/hallon/session.rb:50:in `new'
    from /app/vendor/bundle/ruby/1.9.1/gems/hallon-0.18.2/lib/hallon/session.rb:50:in `initialize'
    from (irb):2
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by Burgestrand** [comment]
Thanks for the bug report. This is a strange issue. The line from your stack trace implies that this code returns `nil`:

``` ruby
@enum ||= Spotify.enum_type(:error)
```

I don’t know how that could possibly happen, but I’ll have a look.

**Comment by Burgestrand** [comment]
I’ve upgraded [hallon-heroku to v0.18.2](https://github.com/Burgestrand/hallon-heroku), and it runs fine.

@cptobvious Could you possibly share the source code to an example that fails in the way you’ve described?

**Comment by chrblabla** [comment]
I found out that I still had a custom initializer which would setup FFI to correctly load Hallon. After I removed it, everything works as expected and I made sure that the Gemfile does require both gems.
Thanks a ton for the quick response though!

For your information, this was the custom initializer:

``` ruby
if ["staging", "production"].include?(Rails.env)
  require "ffi"

  module Spotify
    module Heroku
      def self.libspotify_path
        "/app/vendor/spotify/libspotify.so"
      end

      def ffi_lib(*)
        super(ENV["SPOTIFY_LIBRARY"])
      end
    end

    extend FFI::Library
    extend Spotify::Heroku
  end
end

require "spotify"
require "hallon"
```

**Comment by Burgestrand** [comment]
Ah, yes, the old initializer. Thankfully it should no longer be needed, with the [libspotify gem](http://rubygems.org/gems/libspotify) available on Heroku! :)
