### ISSUE TITLE
`attach_function': Function 'sp_build_id' not found in [libspotify.dylib]

### ISSUE THREAD

**Issue by jonrohan** [Burgestrand/Hallon#92]
Pardon if this is not an issue but when I try `require 'hallon'` my script errors.

Gem list

```
gem list

*** LOCAL GEMS ***

ffi (1.0.11)
hallon (0.14.0)
nokogiri (1.5.2)
rainbow (1.1.3)
rake (0.9.2.2)
ref (1.0.0)
spotify (10.3.0)
```

Ruby version

```
ruby -v
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.3.0]
```

Trace back

```
/Users/jonrohan/.rvm/gems/ruby-1.9.2-p290/gems/ffi-1.0.11/lib/ffi/library.rb:249:in `attach_function': Function 'sp_build_id' not found in [libspotify.dylib] (FFI::NotFoundError)
    from /Users/jonrohan/.rvm/gems/ruby-1.9.2-p290/gems/spotify-10.3.0/lib/spotify.rb:69:in `attach_function'
    from /Users/jonrohan/.rvm/gems/ruby-1.9.2-p290/gems/spotify-10.3.0/lib/spotify.rb:136:in `<module:Spotify>'
    from /Users/jonrohan/.rvm/gems/ruby-1.9.2-p290/gems/spotify-10.3.0/lib/spotify.rb:11:in `<top (required)>'
    from /Users/jonrohan/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jonrohan/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jonrohan/.rvm/gems/ruby-1.9.2-p290/gems/hallon-0.14.0/lib/hallon.rb:2:in `<top (required)>'
    from /Users/jonrohan/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /Users/jonrohan/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /Users/jonrohan/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
```

**Comment by Burgestrand** [comment]
Hi! You have an old version of libspotify installed. Hallon only support the most recent release (10.1.16).

I should make that fact more apparent however; thanks for reporting the issue though. :)

**Comment by jonrohan** [comment]
thanks
